server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#        dialect: org.hibernate.dialect.H2Dialect
#    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: 'jdbc:mysql://localhost:3306/TESTJPA'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: TEST
    password: TEST

#    url: 'jdbc:h2:~/test'
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
